//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCustomWidgetExtension\src\main\java\com\ashera\customwidgetextension\CustomWidgetExtensionViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomWidgetExtensionViewImpl")
#ifdef RESTRICT_CustomWidgetExtensionViewImpl
#define INCLUDE_ALL_CustomWidgetExtensionViewImpl 0
#else
#define INCLUDE_ALL_CustomWidgetExtensionViewImpl 1
#endif
#undef RESTRICT_CustomWidgetExtensionViewImpl

#if !defined (ASCustomWidgetExtensionViewImpl_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl))
#define ASCustomWidgetExtensionViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean;
@class ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder;
@class ASWidgetAttribute;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASCustomWidgetExtensionViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean *)getBean;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)getBuilder;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

+ (void)nativeSetFrameForCAGradientLayerWithId:(id)nativeWidget;

+ (void)nativeSetLinearGradientBackgroundWithId:(id)nativeWidget
                                         withId:(id)color1
                                         withId:(id)color2;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl)

inline NSString *ASCustomWidgetExtensionViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCustomWidgetExtensionViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCustomWidgetExtensionViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_init(ASCustomWidgetExtensionViewImpl *self);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl *new_ASCustomWidgetExtensionViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl *create_ASCustomWidgetExtensionViewImpl_init(void);

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_nativeSetFrameForCAGradientLayerWithId_(id nativeWidget);

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_nativeSetLinearGradientBackgroundWithId_withId_withId_(id nativeWidget, id color1, id color2);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl)

@compatibility_alias ComAsheraCustomwidgetextensionCustomWidgetExtensionViewImpl ASCustomWidgetExtensionViewImpl;

#endif

#if !defined (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder))
#define ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewCommandBuilder 1
#include "ViewImpl.h"

@class ASCustomWidgetExtensionViewImpl;

@interface ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder : ASViewImpl_ViewCommandBuilder

#pragma mark Public

- (instancetype)initWithASCustomWidgetExtensionViewImpl:(ASCustomWidgetExtensionViewImpl *)outer$;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)invalidate;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)requestLayout;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)reset;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setEnabledWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setLinearGradientBackgroundWithNSString:(NSString *)value;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetAlpha;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetBackground;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetBackgroundTint;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetBackgroundTintMode;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetClickable;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetContentDescription;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetDuplicateParentState;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetEnabled;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetFocusable;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetForeground;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetForegroundGravity;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetForegroundTint;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetForegroundTintMode;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetId;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAccessibilityHint;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAccessibilityValue;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAlpha;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosBackgroundColor;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosClipsToBounds;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosContentScaleFactor;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsFocused;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsHidden;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsOpaque;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosLargeContentImage;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosLargeContentTitle;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosTag;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosTintColor;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetKeepScreenOn;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetLayoutDirection;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetLongClickable;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetMaxHeight;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetMaxWidth;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetMinHeight;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetMinWidth;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetModelParam;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetModelPojoToUi;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetModelSyncEvents;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetModelUiToPojo;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetRotation;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetRotationX;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetRotationY;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetScaleX;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetScaleY;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetSelected;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTextAlignment;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTextDirection;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTransformPivotX;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTransformPivotY;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTranslationX;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTranslationY;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetTranslationZ;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetValidateForm;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)tryGetVisibility;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                                                  withId:(id)arg1;

- (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *self, ASCustomWidgetExtensionViewImpl *outer$);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *new_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder *create_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewCommandBuilder)

#endif

#if !defined (ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean))
#define ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean_

#define RESTRICT_ViewImpl 1
#define INCLUDE_ASViewImpl_ViewBean 1
#include "ViewImpl.h"

@class ASCustomWidgetExtensionViewImpl;
@protocol ASIWidget;

@interface ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean : ASViewImpl_ViewBean

#pragma mark Public

- (instancetype)initWithASCustomWidgetExtensionViewImpl:(ASCustomWidgetExtensionViewImpl *)outer$;

- (void)setLinearGradientBackgroundWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean *self, ASCustomWidgetExtensionViewImpl *outer$);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean *new_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean *create_ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean_initWithASCustomWidgetExtensionViewImpl_(ASCustomWidgetExtensionViewImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl_CustomWidgetExtensionViewBean)

#endif

#if !defined (ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler))
#define ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@protocol ASIWidget;

@interface ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)type
                   withASIWidget:(id<ASIWidget>)widget;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *self, NSString *type, id<ASIWidget> widget);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *new_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(NSString *type, id<ASIWidget> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *create_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(NSString *type, id<ASIWidget> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_CustomWidgetExtensionViewImpl")
