//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCustomWidgetExtension\src\main\java\com\ashera\customwidgetextension\CustomWidgetExtensionViewImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomWidgetExtensionViewImpl")
#ifdef RESTRICT_CustomWidgetExtensionViewImpl
#define INCLUDE_ALL_CustomWidgetExtensionViewImpl 0
#else
#define INCLUDE_ALL_CustomWidgetExtensionViewImpl 1
#endif
#undef RESTRICT_CustomWidgetExtensionViewImpl

#if !defined (ASCustomWidgetExtensionViewImpl_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl))
#define ASCustomWidgetExtensionViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASWidgetAttribute;
@class NSString;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASCustomWidgetExtensionViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

+ (void)nativeSetFrameForCAGradientLayerWithId:(id)nativeWidget;

+ (void)nativeSetLinearGradientBackgroundWithId:(id)nativeWidget
                                         withId:(id)color1
                                         withId:(id)color2;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl)

inline NSString *ASCustomWidgetExtensionViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASCustomWidgetExtensionViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASCustomWidgetExtensionViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_init(ASCustomWidgetExtensionViewImpl *self);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl *new_ASCustomWidgetExtensionViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl *create_ASCustomWidgetExtensionViewImpl_init(void);

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_nativeSetFrameForCAGradientLayerWithId_(id nativeWidget);

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_nativeSetLinearGradientBackgroundWithId_withId_withId_(id nativeWidget, id color1, id color2);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl)

@compatibility_alias ComAsheraCustomwidgetextensionCustomWidgetExtensionViewImpl ASCustomWidgetExtensionViewImpl;


#endif

#if !defined (ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_) && (INCLUDE_ALL_CustomWidgetExtensionViewImpl || defined(INCLUDE_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler))
#define ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_

#define RESTRICT_EventBusHandler 1
#define INCLUDE_ASEventBusHandler 1
#include "EventBusHandler.h"

@class NSString;
@protocol ASIWidget;

@interface ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler : ASEventBusHandler

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)type
                   withASIWidget:(id<ASIWidget>)widget;

#pragma mark Protected

- (void)doPerformWithId:(id)payload;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler)

FOUNDATION_EXPORT void ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *self, NSString *type, id<ASIWidget> widget);

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *new_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(NSString *type, id<ASIWidget> widget) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler *create_ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler_initWithNSString_withASIWidget_(NSString *type, id<ASIWidget> widget);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtensionViewImpl_PostMeasureEventHandler)


#endif

#pragma pop_macro("INCLUDE_ALL_CustomWidgetExtensionViewImpl")
