//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCustomWidgetExtension\src\main\java\com\ashera\customwidgetextension\CustomWidgetExtension.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CustomWidgetExtension")
#ifdef RESTRICT_CustomWidgetExtension
#define INCLUDE_ALL_CustomWidgetExtension 0
#else
#define INCLUDE_ALL_CustomWidgetExtension 1
#endif
#undef RESTRICT_CustomWidgetExtension

#if !defined (ASCustomWidgetExtension_) && (INCLUDE_ALL_CustomWidgetExtension || defined(INCLUDE_ASCustomWidgetExtension))
#define ASCustomWidgetExtension_

@interface ASCustomWidgetExtension : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASCustomWidgetExtension)

FOUNDATION_EXPORT void ASCustomWidgetExtension_init(ASCustomWidgetExtension *self);

FOUNDATION_EXPORT ASCustomWidgetExtension *new_ASCustomWidgetExtension_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASCustomWidgetExtension *create_ASCustomWidgetExtension_init(void);

FOUNDATION_EXPORT void ASCustomWidgetExtension_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASCustomWidgetExtension)

@compatibility_alias ComAsheraCustomwidgetextensionCustomWidgetExtension ASCustomWidgetExtension;

#endif

#pragma pop_macro("INCLUDE_ALL_CustomWidgetExtension")
