//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCustomWidgetExtension\src\main\java\com\ashera\customwidgetextension\CustomWidgetExtension.java
//

#include "CustomWidgetExtension.h"
#include "CustomWidgetExtensionViewImpl.h"
#include "J2ObjC_source.h"
#include "WidgetFactory.h"


@implementation ASCustomWidgetExtension

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASCustomWidgetExtension_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASCustomWidgetExtension_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASCustomWidgetExtension = { "CustomWidgetExtension", "com.ashera.customwidgetextension", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASCustomWidgetExtension;
}

@end

void ASCustomWidgetExtension_init(ASCustomWidgetExtension *self) {
  NSObject_init(self);
}

ASCustomWidgetExtension *new_ASCustomWidgetExtension_init() {
  J2OBJC_NEW_IMPL(ASCustomWidgetExtension, init)
}

ASCustomWidgetExtension *create_ASCustomWidgetExtension_init() {
  J2OBJC_CREATE_IMPL(ASCustomWidgetExtension, init)
}

void ASCustomWidgetExtension_initPlugin() {
  ASCustomWidgetExtension_initialize();
  ASWidgetFactory_registerAttributableForWithNSString_withASIAttributable_(@"View", new_ASCustomWidgetExtensionViewImpl_init());
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASCustomWidgetExtension)
